apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: echo
  labels:
    app: curl
spec:
  containers:
    - name: curl
      image: curlimages/curl:8.7.1
      command: ["sleep", "infinity"]
      tty: true